#!/bin/zsh

LC_ALL=C join <(for f in $@
do
	awk '$1 == "ENCODING" { printf("%04X\n", $2) }' <"$f"
done | LC_ALL=C sort -k 1b,1) \
     <(tool/unicode-name unicode/UnicodeData.txt | LC_ALL=C sort -k 1b,1)
